
#include "./capitoli/0_0_cover.typ"
#include "./capitoli/0_1_prima_pagina.typ"
#include "./capitoli/1_0_i_fratelli_di_mowgli.typ"
#include "./capitoli/1_1_la_caccia_di_kaa.typ"
#include "./capitoli/1_2_come_venne_la_paura.typ"
#include "./capitoli/1_3_il_fiore_rosso.typ"
#include "./capitoli/1_4_la_tigre_la_tigre.typ"
#include "./capitoli/1_5_l_invasione_della_giungla.typ"
#include "./capitoli/1_6_l_ankus_del_re.typ"
#include "./capitoli/1_7_i_cani_rossi.typ"
#include "./capitoli/1_8_la_corsa_di_primavera.typ"
#include "./capitoli/2_0_appendice.typ"
